[package]
name = "findanything-windows"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "findanything"
path = "src/main.rs"

[features]
default = ["semantic"]
semantic = ["findanything-ui/semantic"]

[target.'cfg(windows)'.dependencies]
findanything-ui = { path = "../shared", default-features = false }
