#!/usr/bin/env python3
"""Compile the pinned Lucide SVG subset into identical native stroke paths.

Only the primitives in our six vendored icons are supported. Circular arcs are
flattened at <= pi/32 radians per segment (under .01 view-box units error).
Unsupported SVG must fail rather than silently produce a different icon.
"""
import argparse
import math
from pathlib import Path
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent
ICONS = ("app-window", "file", "sliders-horizontal", "search", "menu", "x")


def arc(start, end, radius, large, sweep):
    dx, dy = (start[0] - end[0]) / 2, (start[1] - end[1]) / 2
    distance = dx * dx + dy * dy
    radius = max(radius, math.sqrt(distance))
    factor = math.sqrt(max(0, (radius * radius - distance) / distance))
    if large == sweep:
        factor = -factor
    cx, cy = (start[0] + end[0]) / 2 + factor * dy, (start[1] + end[1]) / 2 - factor * dx
    angle = math.atan2(start[1] - cy, start[0] - cx)
    delta = (math.atan2(end[1] - cy, end[0] - cx) - angle) % math.tau
    if not sweep:
        delta -= math.tau
    steps = max(1, math.ceil(abs(delta) / (math.pi / 32)))
    points = [(cx + radius * math.cos(angle + delta * i / steps), cy + radius * math.sin(angle + delta * i / steps)) for i in range(1, steps)]
    return points + [end]


def path_points(data):
    tokens = re.findall(r"[A-Za-z]|[-+]?(?:\d*\.\d+|\d+\.?\d*)(?:[eE][-+]?\d+)?", data)
    paths, current, point, command = [], [], (0, 0), None
    index = 0
    counts = {"M": 2, "L": 2, "H": 1, "V": 1, "A": 7}
    while index < len(tokens):
        if tokens[index].isalpha():
            command = tokens[index]
            index += 1
        op = command.upper()
        if op == "Z":
            current.append(current[0])
            point = current[0]
            command = None
            continue
        if op not in counts:
            raise ValueError(f"Unsupported SVG command {command}")
        count = counts[op]
        values = list(map(float, tokens[index:index + count]))
        if len(values) != count:
            raise ValueError("Truncated SVG path")
        index += count
        relative = command.islower()
        x, y = point
        if op in ("M", "L", "A"):
            end = (values[-2] + (x if relative else 0), values[-1] + (y if relative else 0))
        elif op == "H":
            end = (values[0] + (x if relative else 0), y)
        else:
            end = (x, values[0] + (y if relative else 0))
        if op == "M":
            current = [end]
            paths.append(current)
            command = "l" if relative else "L"
        elif op == "A":
            rx, ry, rotation, large, sweep = values[:5]
            if rx != ry or rotation != 0 or rx <= 0 or large not in (0, 1) or sweep not in (0, 1):
                raise ValueError("Only unrotated circular SVG arcs are supported")
            current.extend(arc(point, end, rx, large, sweep))
        else:
            current.append(end)
        point = end
    return paths


def load_icon(path):
    root = ET.parse(path).getroot()
    expected = {"viewBox": "0 0 24 24", "fill": "none", "stroke": "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round"}
    if any(root.get(key) != value for key, value in expected.items()):
        raise ValueError(f"Unexpected icon style: {path}")
    paths = []
    for node in root:
        tag = node.tag.rsplit("}", 1)[-1]
        if tag == "path":
            paths.extend(path_points(node.attrib["d"]))
        elif tag == "circle":
            x, y, r = (float(node.attrib[k]) for k in ("cx", "cy", "r"))
            points = [(x + r * math.cos(math.tau * i / 64), y + r * math.sin(math.tau * i / 64)) for i in range(64)]
            paths.append(points + [points[0]])
        elif tag == "rect":
            x, y, w, h, r = (float(node.attrib[k]) for k in ("x", "y", "width", "height", "rx"))
            paths.extend(path_points(f"M{x+r} {y}H{x+w-r}a{r} {r} 0 0 1 {r} {r}V{y+h-r}a{r} {r} 0 0 1 {-r} {r}H{x+r}a{r} {r} 0 0 1 {-r} {-r}V{y+r}a{r} {r} 0 0 1 {r} {-r}Z"))
        else:
            raise ValueError(f"Unsupported SVG element {tag}")
    return paths


def outputs():
    rust = ["// Generated by design/generate_icons.py from vendored Lucide SVGs. Do not edit.", "// License: lucide/LICENSE (ISC and MIT).", "pub const VIEWBOX: f64 = 24.0;", "pub const STROKE_WIDTH: f64 = 2.0;", "#[derive(Clone, Copy)]", "pub enum Icon { AppWindow, File, SlidersHorizontal, Search, Menu, X }", "impl Icon {", "    #[rustfmt::skip]", "    pub fn paths(self) -> &'static [&'static [(f64, f64)]] {", "        match self {"]
    swift = ["// Generated by design/generate_icons.py from vendored Lucide SVGs. Do not edit.", "// License: design/lucide/LICENSE (ISC and MIT).", "import AppKit", "", "enum LucideIcon {", "    case appWindow, file, slidersHorizontal, search, menu, x", "    static let viewbox: CGFloat = 24", "    static let strokeWidth: CGFloat = 2", "    var paths: [[NSPoint]] {", "        switch self {"]
    for name in ICONS:
        pascal = "".join(part.title() for part in name.split("-"))
        paths = load_icon(ROOT / "lucide" / f"{name}.svg")
        rust.append(f"            Self::{pascal} => &[")
        swift.append(f"        case .{pascal[0].lower() + pascal[1:]}: return [")
        for points in paths:
            coords = [(f"{x:.6f}", f"{y:.6f}") for x, y in points]
            rust.append("                &[" + ", ".join(f"({x}, {y})" for x, y in coords) + "],")
            swift.append("            [" + ", ".join(f"NSPoint(x: {x}, y: {y})" for x, y in coords) + "],")
        rust.append("            ],")
        swift.append("        ]")
    rust.extend(["        }", "    }", "}"])
    swift.extend(["        }", "    }", "}"])
    return {ROOT / "lucide.rs": "\n".join(rust) + "\n", ROOT.parent / "macos/Sources/FindAnythingNative/Lucide.swift": "\n".join(swift) + "\n"}


def main():
    parser = argparse.ArgumentParser(__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                parser.exit(1, f"Stale Lucide output: {path.name}; run uv run --no-project python apps/native/design/generate_icons.py\n")
        else:
            path.write_text(content)
    print("Lucide icons: " + ("up to date" if args.check else "generated"))


if __name__ == "__main__":
    main()
