#!/usr/bin/env python3
"""Generate native Graphite tokens. --check fails if any client has drifted."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def outputs():
    tokens = json.loads((ROOT / "tokens.json").read_text())
    rust = ["// Generated by apps/native/design/generate.py; do not edit."]
    swift = ["// Generated by apps/native/design/generate.py; do not edit.", "import AppKit", "", "enum Graphite {"]
    css = ["/* Generated by apps/native/design/generate.py; do not edit. */"]
    for name, value in tokens["colors"].items():
        rgb = int(value[1:], 16)
        rust.append(f"pub const {name.upper()}: u32 = 0x{rgb:06x};")
        swift.append(f"    static let {name} = NSColor(srgbRed: {rgb >> 16} / 255.0, green: {(rgb >> 8) & 255} / 255.0, blue: {rgb & 255} / 255.0, alpha: 1)")
        css.append(f"@define-color graphite_{name} {value};")
    for name, value in tokens["metrics"].items():
        rust.append(f"pub const {name.upper()}: i32 = {value};")
        swift.append(f"    static let {name}: CGFloat = {value}")
    swift.append("}")
    return {
        ROOT / "graphite.rs": "\n".join(rust) + "\n",
        ROOT / "colors.css": "\n".join(css) + "\n",
        ROOT.parent / "macos/Sources/FindAnythingNative/Graphite.swift": "\n".join(swift) + "\n",
    }


def main():
    parser = argparse.ArgumentParser(__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT.parent)))
        else:
            path.write_text(content)
    if stale:
        parser.exit(1, "Stale Graphite tokens: " + ", ".join(stale) + "\nRun python apps/native/design/generate.py\n")
    print("Graphite tokens: " + ("up to date" if args.check else "generated"))


if __name__ == "__main__":
    main()
