// Generated by apps/native/design/generate.py; do not edit.
import AppKit

enum Graphite {
    static let bg = NSColor(srgbRed: 22 / 255.0, green: 22 / 255.0, blue: 24 / 255.0, alpha: 1)
    static let chrome = NSColor(srgbRed: 28 / 255.0, green: 28 / 255.0, blue: 30 / 255.0, alpha: 1)
    static let control = NSColor(srgbRed: 42 / 255.0, green: 42 / 255.0, blue: 45 / 255.0, alpha: 1)
    static let control_hover = NSColor(srgbRed: 50 / 255.0, green: 50 / 255.0, blue: 53 / 255.0, alpha: 1)
    static let control_active = NSColor(srgbRed: 58 / 255.0, green: 58 / 255.0, blue: 61 / 255.0, alpha: 1)
    static let popover = NSColor(srgbRed: 38 / 255.0, green: 38 / 255.0, blue: 41 / 255.0, alpha: 1)
    static let hairline = NSColor(srgbRed: 32 / 255.0, green: 32 / 255.0, blue: 35 / 255.0, alpha: 1)
    static let border = NSColor(srgbRed: 42 / 255.0, green: 42 / 255.0, blue: 45 / 255.0, alpha: 1)
    static let border_strong = NSColor(srgbRed: 53 / 255.0, green: 53 / 255.0, blue: 56 / 255.0, alpha: 1)
    static let text_strong = NSColor(srgbRed: 245 / 255.0, green: 245 / 255.0, blue: 247 / 255.0, alpha: 1)
    static let text = NSColor(srgbRed: 232 / 255.0, green: 232 / 255.0, blue: 234 / 255.0, alpha: 1)
    static let secondary = NSColor(srgbRed: 199 / 255.0, green: 199 / 255.0, blue: 204 / 255.0, alpha: 1)
    static let muted = NSColor(srgbRed: 160 / 255.0, green: 160 / 255.0, blue: 166 / 255.0, alpha: 1)
    static let faint = NSColor(srgbRed: 128 / 255.0, green: 128 / 255.0, blue: 135 / 255.0, alpha: 1)
    static let accent = NSColor(srgbRed: 76 / 255.0, green: 154 / 255.0, blue: 255 / 255.0, alpha: 1)
    static let accent_strong = NSColor(srgbRed: 59 / 255.0, green: 120 / 255.0, blue: 199 / 255.0, alpha: 1)
    static let accent_text = NSColor(srgbRed: 125 / 255.0, green: 182 / 255.0, blue: 255 / 255.0, alpha: 1)
    static let selected = NSColor(srgbRed: 30 / 255.0, green: 40 / 255.0, blue: 56 / 255.0, alpha: 1)
    static let danger = NSColor(srgbRed: 255 / 255.0, green: 138 / 255.0, blue: 128 / 255.0, alpha: 1)
    static let window_width: CGFloat = 680
    static let window_height: CGFloat = 440
    static let minimum_width: CGFloat = 560
    static let minimum_height: CGFloat = 360
    static let inset: CGFloat = 20
    static let gap: CGFloat = 8
    static let search_height: CGFloat = 52
    static let section_height: CGFloat = 24
    static let row_height: CGFloat = 60
    static let footer_height: CGFloat = 28
    static let icon_size: CGFloat = 20
    static let radius: CGFloat = 9
    static let search_size: CGFloat = 18
    static let body_size: CGFloat = 16
    static let metadata_size: CGFloat = 12
}
